package org.oltp1.runner.generator;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;

class TradeTrackerTest
{
    @Test
    void testRecordNewTradeId_NormalizesShiftedId()
    {
        long unshiftedInitialMax = 2_592_000L;
        LocalDateTime initialEndDts =
                LocalDateTime.of(2025, 1, 1, 17, 0, 0);

        // Initialize with shifted ID (as returned by DB)
        long shiftedInitialMax =
                unshiftedInitialMax + TradeTracker.TRADE_SHIFT;

        TradeTracker tracker =
                new TradeTracker(shiftedInitialMax, initialEndDts);

        assertEquals(
                unshiftedInitialMax,
                tracker.getMaxActiveTradeId());

        // Record a new trade generated by DB sequence
        // with TRADE_SHIFT included
        long newGeneratedDbTradeId =
                TradeTracker.TRADE_SHIFT + 2_592_050L;

        tracker.recordNewTradeId(newGeneratedDbTradeId);

        assertEquals(
                2_592_050L,
                tracker.getMaxActiveTradeId());

        // Ensure GenUtils.nonUniformTradeId produces trade IDs
        // in the valid 200T range, never 400T
        CRandom random = new CRandom(12345L);

        for (int i = 0; i < 100; i++)
        {
            long tradeId = GenUtils.nonUniformTradeId(
                    random,
                    tracker.getMaxActiveTradeId(),
                    65535,
                    7);

            assertTrue(
                    tradeId >= TradeTracker.TRADE_SHIFT,
                    "Trade ID must be >= TRADE_SHIFT");

            assertTrue(
                    tradeId <= TradeTracker.TRADE_SHIFT + 2_592_050L,
                    "Trade ID must be <= 200T + maxActiveTradeId");
        }
    }

    @Test
    void testRecordNewTradeId_UnshiftedInput()
    {
        LocalDateTime initialEndDts =
                LocalDateTime.of(2025, 1, 1, 17, 0, 0);

        TradeTracker tracker =
                new TradeTracker(1000L, initialEndDts);

        tracker.recordNewTradeId(1050L);

        assertEquals(
                1050L,
                tracker.getMaxActiveTradeId());

        // Smaller trade ID does not decrease max
        tracker.recordNewTradeId(500L);

        assertEquals(
                1050L,
                tracker.getMaxActiveTradeId());
    }
}