services:
  postgres:
    image: postgres:latest
    container_name: ${PG_CONTAINER_NAME:-pg_oltp1}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-main_db}
    volumes:
      - type: bind
        source: ./custom_postgresql.conf
        target: /etc/postgresql/postgresql.conf
        read_only: true
      - type: bind
        source: ./custom_pg_hba.conf
        target: /etc/postgresql/pg_hba.conf
        read_only: true
      - type: bind
        source: ${PGDATA_HOST_PATH:-./pgdata}
        target: /var/lib/postgresql/data
      - type: bind
        source: ${TABLESPACE_HOST_PATH:-./pg_tablespaces}
        target: /mnt/tablespaces
      - ./init:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - ${PG_PORT:-5432}:5432
