CREATE INDEX ix_company_comp_nc1 on company_competitor(cp_co_id);
CREATE UNIQUE INDEX ix_broker_nc1 on broker(b_name, b_id);
CREATE UNIQUE INDEX ix_broker_nc2 on broker(b_id, b_name);
CREATE UNIQUE INDEX ix_company_nc1 on company(co_name, co_id);
CREATE UNIQUE INDEX ix_company_nc2 on company(co_in_id, co_id);
CREATE UNIQUE INDEX ix_customer_account_nc1 on customer_account(ca_c_id, ca_id);
CREATE UNIQUE INDEX ix_customer_nc1 on customer(c_tax_id, c_id);
CREATE UNIQUE INDEX ix_customer_nc2 on customer(c_id, c_tier);
CREATE UNIQUE INDEX ix_holding_history_nc1 on holding_history(hh_t_id, hh_h_t_id);
CREATE UNIQUE INDEX ix_holding_nc1 on holding(h_ca_id, h_s_symb, h_dts, h_t_id);
CREATE UNIQUE INDEX ix_industry_nc1 on industry(in_name, in_id);
CREATE UNIQUE INDEX ix_sector_nc1 on sector(sc_name, sc_id);
CREATE UNIQUE INDEX ix_security_nc1 on security(s_co_id, s_issue, s_ex_id, s_symb);
CREATE UNIQUE INDEX ix_trade_nc1 on trade(t_ca_id, t_dts, t_id);
CREATE UNIQUE INDEX ix_trade_nc2 on trade(t_s_symb, t_dts, t_id);
CREATE UNIQUE INDEX ix_trade_request_nc1 on trade_request(tr_b_id asc, tr_s_symb asc, tr_t_id asc);
CREATE UNIQUE INDEX ix_trade_request_nc2 on trade_request(tr_s_symb, tr_t_id, tr_tt_id, tr_bid_price, tr_qty);
CREATE UNIQUE INDEX ix_watch_list_nc1 on watch_list(wl_c_id, wl_id);