UNLOCK TABLES;

LOCK TABLE trade WRITE;

SELECT @next := COALESCE(MAX(t_id), 0) + 1
FROM trade;

SET @sql := CONCAT('ALTER TABLE trade AUTO_INCREMENT = ', @next);
PREPARE s FROM @sql;
EXECUTE s;
DEALLOCATE PREPARE s;

UNLOCK TABLES;
